### ISSUE TITLE
redirectURI does not work with anything besides localhost

### ISSUE THREAD

**Issue by pedrovelho** [openpubkey/openpubkey#335]
## Description

When using `redirect_uri` in the config file with anything besides localhost causes standard_provider.go to fail.

## How to reproduce

*Disclaimer*: The only way I know how to reproduce this for now is with opkssh client. By the way, this started as a discussion in opkssh project here: https://github.com/openpubkey/opkssh/discussions/227

Create a `config.yml` configuration:

```yaml
default_provider: keycloak

providers:
  - alias: keycloak
    issuer: https://keycloak.mydomain.org/auth/realms/myrealm
    client_id: opkssh-client
    scopes: openid profile email groups
    redirect_uris:
      - http://myserver.mydomain.org/login-callback
```

Download and install latest opkssh client.

```shell
curl -L https://github.com/openpubkey/opkssh/releases/latest/download/opkssh-linux-amd64 -o ~/opkssh; chmod +x ~/opkssh
```

Run the client with the `config.yml` file.

```shell
~/opkssh login --config-path ./config.yml 
```

## Current Behavior

The client show the following error:

```log
2025/06/19 16:14:26 Error executing login command: error logging in: error requesting OIDC tokens from OpenID Provider: redirectURI must be localhost, redirectURI was myserver.mydomain.org
Error: error logging in: error requesting OIDC tokens from OpenID Provider: redirectURI must be localhost, redirectURI was  myserver.ryax.io
```

## Expected Behavior

Should accept connections on localhost but generate the login redirectURI to the correct location.

## Leads

I created a branch where I tried simply to remove the condition that checks for the correct redirectURI and made it listen on localhost, for me the problem is that redirectURI should not be the same address used to listen on. 
https://github.com/RyaxTech/openpubkey/blob/pedrovelho-patch-1/providers/utils.go#L50
